
#include<stdio.h>
int main()
{
    int a;
    printf("enter a one number");
    scanf("%d",&a);

    switch(a)
{
    case 1: printf("one");
    break;
    case 2 : printf("two");
    break;
    case 3 : printf("three");
    break;
    case 4 : printf("four");
    break;
    case 5 : printf("five");
    break;
    case 6 : printf("six");
    break;
    case 7 : printf("seven");
    break;
    case 8 : printf("eight");
    break;
    case 9 : printf("nine");
    break;
    case 10 : printf("ten");
    break;
    case 11 : printf("eleven");
    break;
    case 12: printf("twell");
    break;
    case 13 : printf("thirteen");
    break;
    case 14 : printf("fourteen");
    break;
    case 15 : printf("fifteen");
    break;
    case 16 : printf("sisxteen");
    break;
    case 17 : printf("seventeen");
    break;
    case 18 : printf("eighteen");
    break;
    case 19 : printf("nineteen");
    break;
    case 20: printf("twenty");
    break;
    case 21: printf("twentyone");
    break;
    case 22 : printf("twentytwo");
    break;
    case 23 : printf("twentythree");
    break;
    case 24 : printf("twentyfour");
    break;
     case 25: printf("twentyfive");
    break;
    case 26 : printf("twentysix");
    break;
    case 27 : printf("twentyseven");
    break;
    case 28 : printf("twentyeight");
    break;
    case 29: printf("twentynine");
    break;
    case 30 : printf("thirty");
    break;
    case 31 : printf("thirtyone");
    break;
    case 32 : printf("thirtytwo");
    break;
    case 33 : printf("thirtythree");
    break;
    case 34 : printf("thirtyfour");
    break;
    case 35: printf("tthirtyive");
    break;
    case 36 : printf("thirtysix");
    break;
    case 37 : printf("thirtyseven");
    break;
    case 38 : printf("thirtyeight");
    break;
    case 39: printf("thirtynine");
    break;
    case 40 : printf("fourty");
    break;
    case 41 : printf("fourtyyone");
    break;
    case 42 : printf("fourtytwo");
    break;
    case 43 : printf("fourtythree");
    break;
    case 44 : printf("fourtyfour");
    break;
    case 45: printf("fourtyfive");
    break;
    case 46 : printf("fourtysix");
    break;
    case 47 : printf("fourtyseven");
    break;
    case 48 : printf("fourtyeight");
    break;
    case 49: printf("fourtnine");
    break;
    case 50 : printf("fifty");
    break;
    case 51 : printf("fiftyone");
    break;
    case 52 : printf("fiftytwo");
    break;
    case 53 : printf("fiftythree");
    break;
    case 54 : printf("fiftyfour");
    break;
    case 55: printf("fiftyfive");
    break;
    case 56 : printf("fiftysix");
    break;
    case 57 : printf("fiftyseven");
    break;
    case 58 : printf("fiftyeight");
    break;
    case 59: printf("fiftynine");
    break;
    case 60 : printf("sixtyty");
    break;
    case 61 : printf("sixtyone");
    break;
    case 62 : printf("sixtytwo");
    break;
    case 63 : printf("sixtythree");
    break;
    case 64 : printf("sixtyfour");
    break;
    case 65: printf("sixtyfive");
    break;
    case 66 : printf("sixtysix");
    break;
    case 67 : printf("sixtyseven");
    break;
    case 68 : printf("sixtyeight");
    break;
    case 69: printf("sixtnine");
    break;
    case 70 : printf("seventy");
    break;
    case 71 : printf("seventyone");
    break;
    case 72 : printf("seventytwo");
    break;
    case 73 : printf("seventythree");
    break;
    case 74 : printf("seventyfour");
    break;
    case 75: printf("seventyfive");
    break;
    case 76 : printf("seventysix");
    break;
    case 77 : printf("seventyseven");
    break;
    case 78 : printf("seventyeight");
    break;
    case 79: printf("seventynine");
    break;
    case 80 : printf("eightyty");
    break;
    case 81 : printf("eighttyone");
    break;
    case 82 : printf("eightytwo");
    break;
    case 83 : printf("eightythree");
    break;
    case 84 : printf("eightyfour");
    break;
    case 85: printf("eightyfive");
    break;
    case 86 : printf("eightysix");
    break;
    case 87 : printf("eightyseven");
    break;
    case 88 : printf("eightyeight");
    break;
    case 89: printf("eightynine");
    break;
    case 90 : printf("ninety");
    break;
    case 91 : printf("ninetyone");
    break;
    case 92 : printf("ninetytwo");
    break;
    case 93 : printf("ninetythree");
    break;
    case 94 : printf("ninetyfour");
    break;
    case 95: printf("ninetyfive");
    break;
    case 96 : printf("ninetysix");
    break;
    case 97 : printf("ninetyseven");
    break;
    case 98 : printf("ninetyeight");
    break;
    case 99: printf("ninetnine");
    break;
    case 100 : printf("hundred");
    break;
   
}
}